# Generated by Django 2.2.8 on 2020-06-30 11:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_count', models.PositiveIntegerField(default=0)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('following', models.ManyToManyField(blank=True, null=True, related_name='followers', to='tweets.UserProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140)),
                ('type', models.CharField(choices=[('Or', 'Original'), ('Rt', 'Retweet'), ('Rp', 'Reply')], max_length=10)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 6, 30, 11, 20, 23, 933435, tzinfo=datetime.timezone.utc))),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('flags_count', models.PositiveIntegerField(default=0)),
                ('flags', models.ManyToManyField(blank=True, related_name='flagged_tweets', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_tweets', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tweets', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retweetsnreplies', to='tweets.Tweet')),
            ],
        ),
    ]
