# Generated by Django 2.2.8 on 2020-06-30 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20200630_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 11, 28, 3, 746820, tzinfo=datetime.timezone.utc)),
        ),
    ]
