# Generated by Django 2.2.8 on 2020-06-30 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20200630_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 11, 35, 23, 330063, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='type',
            field=models.CharField(choices=[('Original', 'Original'), ('Retweet', 'Retweet'), ('Reply', 'Reply')], max_length=10),
        ),
    ]
