# Generated by Django 2.2.8 on 2020-06-30 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20200630_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 11, 38, 20, 99033, tzinfo=datetime.timezone.utc)),
        ),
    ]
