# Generated by Django 2.2.8 on 2020-07-04 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_auto_20200701_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 4, 20, 43, 21, 795274, tzinfo=datetime.timezone.utc)),
        ),
    ]
