# Generated by Django 2.2.8 on 2020-07-05 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_auto_20200705_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='following_count',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 4, 34, 34, 930347, tzinfo=datetime.timezone.utc)),
        ),
    ]
