# Generated by Django 2.2.8 on 2020-07-07 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_auto_20200705_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='flags_count',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='likes_count',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 9, 7, 41, 147545, tzinfo=datetime.timezone.utc)),
        ),
    ]
